version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node18:latest

    container_name: edutube-node18

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "1640:1640"
    command: >
      sh -c "npm i --force &&
             npm start"


#Docker Networks
#Docker Networks

networks:
  default:
    external:
      name: webskitters
